# Tensor Flow Fundamentals

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and Numpys
* using @tf.function
* using GPU with TensorFlow (or TPUs)


# Introduction to Tensors

In [ ]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
#Creating tensor using tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Checking the no of dimensions of a tensor (ndim means the number of dimensions)
scalar.ndim

0

In [ ]:
#Creating a vector
vector = tf.constant([[10,10],[20,30]])
vector

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [20, 30]], dtype=int32)>

In [ ]:
vector.ndim

2

In [ ]:
#Creating a matrix
matrix = tf.constant([[1,2,3],[4,5,6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
#Creating another matrix and specify the dtype
float_matrix = tf.constant([[3.,4.,5.],
                            [2.,1.,5.],
                            [0.,9.,6]], dtype=tf.float16)
float_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[3., 4., 5.],
       [2., 1., 5.],
       [0., 9., 6.]], dtype=float16)>

In [ ]:
float_matrix.ndim

2

In [ ]:
#Creating another tensor
tensor_matrix = tf.constant([[[1,2,3],
                              [4,5,6]],
                             [[2,3,4,],
                             [4,5,6]],
                             [[23,324,13],
                              [3244,32,42]]])
tensor_matrix

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[   1,    2,    3],
        [   4,    5,    6]],

       [[   2,    3,    4],
        [   4,    5,    6]],

       [[  23,  324,   13],
        [3244,   32,   42]]], dtype=int32)>

In [ ]:
tensor_matrix.ndim

3

* Scalar: A single number
* Vector: A number with direction
* Matrix: A 2-dimensional Array
* Tensor: An n-dimensional Array of numbers(including 0-dim,1-dim,2-dim..)

### Creating Tensor with `tf.Variable`

In [ ]:
changeable_tensor = tf.Variable([1,2,4])
changeable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 4], dtype=int32)>

In [ ]:
changeable_tensor[2].assign(3)
changeable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
unchangeable_tensor = tf.constant([1,2,5])
unchangeable_tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 5], dtype=int32)>

In [ ]:
unchangeable_tensor[2].assign(3)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating a random tensor
Random tensor are tensor of arbitary size of random numbers

In [ ]:
#Creating random tensors
random_tensor = tf.random.Generator.from_seed(42)
random_tensor2 = tf.random.Generator.from_seed(42)
random_1 = random_tensor.normal([4,2])
random_2 = random_tensor2.normal([4,2])
random_1 , random_2 , random_1 == random_2

(<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffling a Tensor

In [ ]:
not_shuffled = tf.constant([[1,2,3],
                            [4,5,6],
                            [7,8,9]])
not_shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
not_shuffled.ndim

2

In [ ]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]], dtype=int32)>

In [ ]:
tf.random.set_seed(7)
shuffled = tf.random.shuffle(not_shuffled,seed=7)
shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]], dtype=int32)>

### More ways to create tensors

In [ ]:
zero_tensors = tf.zeros((4,5))
zero_tensors

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
one_tensors = tf.ones((5,6))
one_tensors

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

## Turning numpy array into tensors

The difference between the numpy array and the tensors is tensor runs much faster than the numpy array on GPU

In [ ]:
import numpy as np
numpy_a = np.arange(1,49,2)
numpy_a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47])

In [ ]:
numpy_to_tensor = tf.constant(numpy_a,shape=(3,2,4))
numpy_to_tensor

<tf.Tensor: shape=(3, 2, 4), dtype=int64, numpy=
array([[[ 1,  3,  5,  7],
        [ 9, 11, 13, 15]],

       [[17, 19, 21, 23],
        [25, 27, 29, 31]],

       [[33, 35, 37, 39],
        [41, 43, 45, 47]]])>

In [ ]:
init = tf.constant_initializer(3)
a = tf.Variable(init(shape=[8,3]))
a

<tf.Variable 'Variable:0' shape=(8, 3) dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]], dtype=int32)>

In [ ]:
unit_matrix = np.eye(4)
unit_tensor = tf.constant(unit_matrix,dtype=tf.int32)
unit_tensor

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)>

In [ ]:
type(unit_tensor)

tensorflow.python.framework.ops.EagerTensor

### Getting information from tensors

When dealing with the tensor you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or Dimension
* Size

In [ ]:
rank_4_tensor = tf.ones(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape , rank_4_tensor.ndim , tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
print("Datatype of every element in Tensor : ",rank_4_tensor.dtype)
print("Number of dimensions (Rank) : ",rank_4_tensor.ndim)
print("Shape of Tensor : ",rank_4_tensor.shape)
print("Elements along axis 0 : ",rank_4_tensor.shape[0])
print("Elements along last axis : ",rank_4_tensor.shape[-1])
print("Total elements in the tensor : ",tf.size(rank_4_tensor))
print("Total elements in the tensor : ",tf.size(rank_4_tensor).numpy())

Datatype of every element in Tensor :  <dtype: 'float32'>
Number of dimensions (Rank) :  4
Shape of Tensor :  (2, 3, 4, 5)
Elements along axis 0 :  2
Elements along last axis :  5
Total elements in the tensor :  tf.Tensor(120, shape=(), dtype=int32)
Total elements in the tensor :  120


### Indexing Tensors

Tensors can be indexed just like python

In [ ]:
rank_4_tensor[0,0,0,0:2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:2,:3,:4]

<tf.Tensor: shape=(1, 2, 3, 4), dtype=float32, numpy=
array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[1,1,:,:]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
## Creating a rank 2 tensor (2 dimension)
rank_2_tensor = tf.ones(shape=[3,5])
rank_2_tensor

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(3, 5, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]], dtype=float32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(3, 1, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(3, 5, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]], dtype=float32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.reshape(rank_2_tensor,shape=(3,5,1))

<tf.Tensor: shape=(3, 5, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]], dtype=float32)>

### Manipulating tensor (Tensor Operations)

**Basic Operations :**
  `+` `-` `*` `/`

In [ ]:
tensors = tf.constant([[41,49],[8,9]])
tensors

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[41, 49],
       [ 8,  9]], dtype=int32)>

In [ ]:
tensors+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[51, 59],
       [18, 19]], dtype=int32)>

In [ ]:
tensors - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[31, 39],
       [-2, -1]], dtype=int32)>

In [ ]:
tensors * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[410, 490],
       [ 80,  90]], dtype=int32)>

In [ ]:
tensors/10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[4.1, 4.9],
       [0.8, 0.9]])>

In [ ]:
# Using TensorFlow in-build functions
tf.multiply(tensors,20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[820, 980],
       [160, 180]], dtype=int32)>

In [ ]:
tf.add(tensors,40)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[81, 89],
       [48, 49]], dtype=int32)>

In [ ]:
tf.subtract(tensors,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[31, 39],
       [-2, -1]], dtype=int32)>

In [ ]:
tf.divide(tensors,2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[20.5, 24.5],
       [ 4. ,  4.5]])>

**Matrix Multiplication**

In Machine Learning, matrix multiplication is one of the common basic tensor operation

In [ ]:
tf.matmul(tensors,tensors)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2073, 2450],
       [ 400,  473]], dtype=int32)>

In [ ]:
a = tf.constant([[1,2,5],
                 [7,2,1],
                 [3,3,3]])
b = tf.constant([[3,5],
                 [6,7],
                 [1,8]])

In [ ]:
tf.matmul(a,b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# The matrix multiplication in python we use @
a @ b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
A = tf.constant([[1,2],
                 [7,2],
                 [3,3]])
B = tf.constant([[3,5],
                 [6,7],
                 [1,8]])

In [ ]:
A @ B

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [ ]:
# Transpose
A,tf.transpose(A), tf.reshape(A,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [7, 2],
        [3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 7, 3],
        [2, 2, 3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 7],
        [2, 3, 3]], dtype=int32)>)

In [ ]:
tf.matmul(A,tf.transpose(A))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11,  9],
       [11, 53, 27],
       [ 9, 27, 18]], dtype=int32)>

**Dot Product**

The matrix multiplication also referred as the dot product

The matrix multiplication can be done :
* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
tf.tensordot(A,tf.transpose(A),axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11,  9],
       [11, 53, 27],
       [ 9, 27, 18]], dtype=int32)>

In [ ]:
A

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [7, 2],
       [3, 3]], dtype=int32)>

In [ ]:
tf.tensordot(A,tf.transpose(A),axes=0)

<tf.Tensor: shape=(3, 2, 2, 3), dtype=int32, numpy=
array([[[[ 1,  7,  3],
         [ 2,  2,  3]],

        [[ 2, 14,  6],
         [ 4,  4,  6]]],


       [[[ 7, 49, 21],
         [14, 14, 21]],

        [[ 2, 14,  6],
         [ 4,  4,  6]]],


       [[[ 3, 21,  9],
         [ 6,  6,  9]],

        [[ 3, 21,  9],
         [ 6,  6,  9]]]], dtype=int32)>

### Changing the datatype of the tensors

In [ ]:
# Create a tensor of datatype float32
P = tf.constant([1.4,3.14])
P, P.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.4 , 3.14], dtype=float32)>,
 tf.float32)

In [ ]:
# Now lets change the dtype of tensor above to int32
D = tf.cast(P, dtype=tf.int32)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>,
 tf.int32)

In [ ]:
S = tf.cast(P, dtype=tf.float16)
S , S.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.4 , 3.14], dtype=float16)>,
 tf.float16)

### Tensor Aggregation

In [ ]:
R = tf.constant(np.random.randint(1,100,[41]))
R

<tf.Tensor: shape=(41,), dtype=int64, numpy=
array([34, 42, 12, 33, 47, 21, 66, 93, 35, 52, 65, 28, 85, 65, 77, 55, 65,
       90, 41, 87, 93, 21, 43, 93, 52,  8, 58, 85, 49, 30, 90, 31, 99, 56,
       47,  2, 65, 56, 56, 25, 88])>

In [ ]:
# Find the minimum value
tf.reduce_min(R)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
# Find the maximum value
tf.reduce_max(R)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
# Mean of the tensor
tf.reduce_mean(R)

<tf.Tensor: shape=(), dtype=int64, numpy=54>

In [ ]:
tf.reduce_sum(R)

<tf.Tensor: shape=(), dtype=int64, numpy=2240>

In [ ]:
tf.reduce_sum(R)/41

<tf.Tensor: shape=(), dtype=float64, numpy=54.63414634146341>

In [ ]:
NegativeTensor = tf.constant([-1.23,-3.14,-4.59])
tf.abs(NegativeTensor)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.23, 3.14, 4.59], dtype=float32)>

In [ ]:
# Variance
X = tf.cast(R,dtype=tf.float32)
X

<tf.Tensor: shape=(41,), dtype=float32, numpy=
array([34., 42., 12., 33., 47., 21., 66., 93., 35., 52., 65., 28., 85.,
       65., 77., 55., 65., 90., 41., 87., 93., 21., 43., 93., 52.,  8.,
       58., 85., 49., 30., 90., 31., 99., 56., 47.,  2., 65., 56., 56.,
       25., 88.], dtype=float32)>

In [ ]:
tf.math.reduce_std(X)

<tf.Tensor: shape=(), dtype=float32, numpy=25.977245>

In [ ]:
tf.math.reduce_variance(X)

<tf.Tensor: shape=(), dtype=float32, numpy=674.8173>

In [ ]:
# The above one is from math now we use the tensorflowprobability
import tensorflow_probability as tfp
tfp.stats.variance(R)

<tf.Tensor: shape=(), dtype=int64, numpy=675>

In [ ]:
tfp.stats.stddev(X)

<tf.Tensor: shape=(), dtype=float32, numpy=25.977245>

### Finding the positional maximum and minimum

In [ ]:
Tensor = tf.random.uniform(shape=(2,25))
Tensor

<tf.Tensor: shape=(2, 25), dtype=float32, numpy=
array([[0.01905346, 0.6496551 , 0.6962069 , 0.5500748 , 0.58857775,
        0.24705338, 0.3295344 , 0.1120199 , 0.6467608 , 0.01355374,
        0.7299129 , 0.03882682, 0.23880851, 0.49790883, 0.85397625,
        0.69668555, 0.5923586 , 0.24508905, 0.31688094, 0.6731936 ,
        0.52317286, 0.02140117, 0.3216492 , 0.5990864 , 0.7901585 ],
       [0.26609623, 0.28422046, 0.6192452 , 0.990942  , 0.10392416,
        0.64259124, 0.11628079, 0.73734283, 0.2591883 , 0.01932311,
        0.530177  , 0.14395463, 0.6720898 , 0.3558743 , 0.73685   ,
        0.16844022, 0.5795028 , 0.78861153, 0.25849175, 0.5669795 ,
        0.25481176, 0.12750673, 0.3559773 , 0.81974554, 0.8130735 ]],
      dtype=float32)>

In [ ]:
tf.argmax(Tensor[0])

<tf.Tensor: shape=(), dtype=int64, numpy=14>

In [ ]:
Tensor[0,tf.argmax(Tensor[0])]

<tf.Tensor: shape=(), dtype=float32, numpy=0.85397625>

In [ ]:
Tensor[1,tf.argmax(Tensor[1])]

<tf.Tensor: shape=(), dtype=float32, numpy=0.990942>

In [ ]:
Tensor[0,tf.argmin(Tensor[0])]

<tf.Tensor: shape=(), dtype=float32, numpy=0.013553739>

In [ ]:
Tensor[1,tf.argmin(Tensor[1])]

<tf.Tensor: shape=(), dtype=float32, numpy=0.01932311>

### Squeezing Tensor (Removing all single dimensions)

In [ ]:
tf.random.set_seed(42)
L = tf.constant(tf.random.uniform(shape=[82]),shape=(2,1,41))
L

<tf.Tensor: shape=(2, 1, 41), dtype=float32, numpy=
array([[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
         0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
         0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
         0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
         0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
         0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
         0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
         0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
         0.23764038]],

       [[0.7817228 , 0.9671384 , 0.06870162, 0.79873943, 0.66028714,
         0.5871513 , 0.16461694, 0.7381023 , 0.32054043, 0.6073899 ,
         0.46523476, 0.97803545, 0.7223145 , 0.32347047, 0.82577336,
         0.4976915 , 0.19483674, 0.7588748 , 0.3380444 , 0.28128064,
         0.31513572, 0.60670924, 0.7498598 , 0.5016055 , 0.18282163,
         0.13179815, 0.6463

In [ ]:
L_squeeze = tf.squeeze(L)
L_squeeze

<tf.Tensor: shape=(2, 41), dtype=float32, numpy=
array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038],
       [0.7817228 , 0.9671384 , 0.06870162, 0.79873943, 0.66028714,
        0.5871513 , 0.16461694, 0.7381023 , 0.32054043, 0.6073899 ,
        0.46523476, 0.97803545, 0.7223145 , 0.32347047, 0.82577336,
        0.4976915 , 0.19483674, 0.7588748 , 0.3380444 , 0.28128064,
        0.31513572, 0.60670924, 0.7498598 , 0.5016055 , 0.18282163,
        0.13179815, 0.64636123, 0.9559475 , 0.

In [ ]:
B = tf.constant(tf.random.uniform(shape=[100]),shape=[1,1,1,1,1,1,1,1,1,1,2,50])
B

<tf.Tensor: shape=(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 50), dtype=float32, numpy=
array([[[[[[[[[[[[0.7413678 , 0.62854624, 0.01738465,
                  0.3431449 , 0.51063764, 0.3777541 ,
                  0.07321596, 0.02137029, 0.2871771 ,
                  0.4710616 , 0.6936141 , 0.07321334,
                  0.93251204, 0.20843053, 0.70105827,
                  0.45856392, 0.8596262 , 0.92934334,
                  0.20291913, 0.76865506, 0.60016024,
                  0.27039742, 0.88180614, 0.05365038,
                  0.42274463, 0.89037776, 0.7887033 ,
                  0.10165584, 0.19408834, 0.27896714,
                  0.39512634, 0.12235212, 0.38412368,
                  0.9455296 , 0.77594674, 0.94442344,
                  0.04296565, 0.4746096 , 0.6548251 ,
                  0.5657116 , 0.13858628, 0.3004663 ,
                  0.3311677 , 0.12907016, 0.6435652 ,
                  0.45473957, 0.68881893, 0.30203617,
                  0.49152803, 0.26529062],
              

In [ ]:
B_squeeze = tf.squeeze(B)
B_squeeze

<tf.Tensor: shape=(2, 50), dtype=float32, numpy=
array([[0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
        0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
        0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
        0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
        0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
        0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
        0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
        0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
        0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
        0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062],
       [0.7122741 , 0.72297084, 0.18866003, 0.24155617, 0.8013923 ,
        0.9717448 , 0.704507  , 0.28954244, 0.5491171 , 0.05062342,
        0.1928184 , 0.4541731 , 0.21889174, 0.87243795, 0.56308484,
        0.316792  , 0.68497694, 0.39252186, 0.7106304 , 0.7038053 

### One-Hot Encoding Tensor

In [ ]:
Lisa = ["Cherry","Oranges","Melons","Banana"]
x = [0,1,2,3]
tf.one_hot(x,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Custom values for the one-hot encoding
tf.one_hot(x,depth=4,off_value="RCB",on_value="IND")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'IND', b'RCB', b'RCB', b'RCB'],
       [b'RCB', b'IND', b'RCB', b'RCB'],
       [b'RCB', b'RCB', b'IND', b'RCB'],
       [b'RCB', b'RCB', b'RCB', b'IND']], dtype=object)>

### Squaring , Logrithms , Square Root

In [ ]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H,dtype=tf.double))

<tf.Tensor: shape=(9,), dtype=float64, numpy=
array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])>

### Tensors and Numpy

TensorFlow interacts with numpy esay. So we can convert the tensor to numpy and numpy to tensor.

In [ ]:
K = tf.constant(np.arange(0,100),shape=[2,50])
K , type(K)

(<tf.Tensor: shape=(2, 50), dtype=int64, numpy=
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
         32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
         48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
         66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
         82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
         98, 99]])>,
 tensorflow.python.framework.ops.EagerTensor)

In [ ]:
np.array(K) , type(np.array(K))

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
         32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
         48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
         66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
         82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
         98, 99]]),
 numpy.ndarray)

In [ ]:
K.numpy() , type(K.numpy())

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
         32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
         48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
         66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
         82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
         98, 99]]),
 numpy.ndarray)

In [ ]:
S = tf.constant([2,3,4],dtype=tf.float32)
S.numpy()[2]

4.0

In [ ]:
Numpy_tensor = tf.constant(np.array([3.,2.,4.]))
Tensor_tensor = tf.constant([2.,3.,4.])
Numpy_tensor.dtype , Tensor_tensor.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [ ]:
import tensorflow as tf
import numpy as np
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Thu Mar 28 16:40:23 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8              12W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

# Exercises

###Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`

In [ ]:
Tensor_Scalar = tf.constant(4)
Tensor_vector = tf.constant([1,2,3])
Tensor_Matrix = tf.constant([[41,2113,24],
                             [34,56,79]])
Tensor = tf.constant(np.arange(1,101),shape=(2,2,25))
Tensor_vector , Tensor_Scalar , Tensor_Matrix , Tensor

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[  41, 2113,   24],
        [  34,   56,   79]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 25), dtype=int64, numpy=
 array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
           13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
           25],
         [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
           38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,
           50]],
 
        [[ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
           63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
           75],
         [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
           88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99,
          100]]])>)

In [ ]:
Tensor.shape , Tensor.ndim , tf.size(Tensor)

(TensorShape([2, 2, 25]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=100>)

In [ ]:
X = tf.random.uniform(shape=[5,300],minval=0,maxval=1)
X

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.01372194, 0.62107086, 0.5302913 , ..., 0.85487866, 0.5186467 ,
        0.45049763],
       [0.7070073 , 0.7664859 , 0.9652598 , ..., 0.92014945, 0.4082259 ,
        0.5325539 ],
       [0.92108345, 0.27768826, 0.25916362, ..., 0.54308224, 0.6476598 ,
        0.6035868 ],
       [0.29539728, 0.42853034, 0.66463935, ..., 0.54650855, 0.77416074,
        0.46840215],
       [0.582423  , 0.04162669, 0.32957506, ..., 0.00368547, 0.3223896 ,
        0.82975125]], dtype=float32)>

In [ ]:
tf.matmul(X,tf.transpose(X))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[104.62802 ,  71.895874,  76.50393 ,  77.93488 ,  76.75569 ],
       [ 71.895874,  95.42788 ,  73.02023 ,  72.46736 ,  76.010895],
       [ 76.50393 ,  73.02023 , 102.24156 ,  73.974144,  75.66153 ],
       [ 77.93488 ,  72.46736 ,  73.974144, 103.61095 ,  77.26959 ],
       [ 76.75569 ,  76.010895,  75.66153 ,  77.26959 ,  99.94704 ]],
      dtype=float32)>

In [ ]:
X * X

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[3.3685267e-01, 1.7685206e-01, 8.0533624e-01, ..., 1.3449298e-01,
        2.5805976e-02, 3.3772278e-01],
       [1.8666431e-03, 1.3406880e-01, 5.2267402e-02, ..., 3.0910155e-02,
        9.7927976e-01, 3.4625668e-02],
       [1.4416457e-02, 5.0857019e-01, 9.3313590e-02, ..., 5.4110732e-02,
        4.5353182e-02, 8.9530736e-02],
       [7.4482298e-01, 5.8036745e-01, 6.0847676e-01, ..., 4.5028201e-04,
        7.7476406e-01, 2.7529476e-03],
       [1.5350485e-02, 2.9023814e-01, 6.3614774e-01, ..., 3.7173784e-01,
        7.9037342e-03, 6.9815107e-02]], dtype=float32)>

In [ ]:
Z = tf.random.uniform(shape=[225,224,3],minval=0,maxval=1)

In [ ]:
tf.argmax(Z[0,0])

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
tf.argmax(Z[0,0])

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
tf.reduce_min(Z[0,0])

<tf.Tensor: shape=(), dtype=float32, numpy=0.09354973>

In [ ]:
Big = tf.constant(np.arange(1,150529),shape=[1,224,224,3])

In [ ]:
tf.squeeze(Big)

<tf.Tensor: shape=(224, 224, 3), dtype=int64, numpy=
array([[[     1,      2,      3],
        [     4,      5,      6],
        [     7,      8,      9],
        ...,
        [   664,    665,    666],
        [   667,    668,    669],
        [   670,    671,    672]],

       [[   673,    674,    675],
        [   676,    677,    678],
        [   679,    680,    681],
        ...,
        [  1336,   1337,   1338],
        [  1339,   1340,   1341],
        [  1342,   1343,   1344]],

       [[  1345,   1346,   1347],
        [  1348,   1349,   1350],
        [  1351,   1352,   1353],
        ...,
        [  2008,   2009,   2010],
        [  2011,   2012,   2013],
        [  2014,   2015,   2016]],

       ...,

       [[148513, 148514, 148515],
        [148516, 148517, 148518],
        [148519, 148520, 148521],
        ...,
        [149176, 149177, 149178],
        [149179, 149180, 149181],
        [149182, 149183, 149184]],

       [[149185, 149186, 149187],
        [149188, 149189,

In [ ]:
final = tf.constant([3,432,14235,532,5,34,24,2,34,4])
tf.argmax(final)

<tf.Tensor: shape=(), dtype=int64, numpy=2>